name: Gradle Assemble
on: [pull_request, workflow_dispatch]

jobs:
  assemble:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Run Gradle (assemble)
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE
