name: Gradle Check (GH)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'backport/**'
      - 'create-pull-request/**'
      - 'dependabot/**'
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenSearch repo
        uses: actions/checkout@v4
        #with:
        #  ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Run Gradle
        run: |
          ./gradlew test check integTest --continue
