name: Gradle Check (GH)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'backport/**'
      - 'create-pull-request/**'
      - 'dependabot/**'
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  gradle-check:
    runs-on: warp-ubuntu-latest-x64-4x
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
    steps:
      - name: Checkout OpenSearch repo
        uses: actions/checkout@v4
        #with:
        #  ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Run gradle check
        run: |
              
              ./gradlew clean || true
              ./gradlew --stop || true
              sleep 2
              rm -rf ~/.gradle || true
              sleep 2
              rm -rf ~/.gradle || true
              ./gradlew check --no-daemon --no-scan --continue --warning-mode=all \
                 --exclude-task :plugins:repository-s3:test \
                 --exclude-task :plugins:repository-s3:s3ThirdPartyTest \
                 --exclude-task :plugins:repository-s3:testRepositoryCreds \
                 --exclude-task :plugins:repository-s3:yamlRestTest \
                 --exclude-task :plugins:repository-s3:yamlRestTestECS \
                 --exclude-task :plugins:repository-s3:yamlRestTestMinio

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: check-test-results-java-${{ matrix.java }}
          path: |
                **/build/reports/tests
