name: Gradle Check Integtest (GH)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'backport/**'
      - 'create-pull-request/**'
      - 'dependabot/**'
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  gradle-check:
    runs-on: warp-ubuntu-latest-x64-4x
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
    steps:
      - name: Checkout OpenSearch repo
        uses: actions/checkout@v4
        #with:
        #  ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Run gradle integTest
        run: |
              ./gradlew integTest --continue
