name: Gradle Check (GH)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'backport/**'
      - 'create-pull-request/**'
      - 'dependabot/**'
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - name: Checkout OpenSearch repo
        uses: actions/checkout@v4
        #with:
        #  ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Run Gradle
        run: |
          ./gradlew test check integTest --continue
