name: Gradle Precommit
on: [pull_request, workflow_dispatch]

jobs:
  precommit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17 ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
      - name: Run Gradle (precommit)
        run: |
          ./gradlew javadoc precommit --parallel --continue
