name: Publish snapshots to maven

env:  
  # SONATYPE_USERNAME SONATYPE_PASSWORD refers to credentials for maven.eliatra.com artifactory
  # We do not use the real sonatype repo for publishing anything, but the variables are hardcoded in upstream code
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

on:
  workflow_dispatch:
  push:
      #branches:
      #  - '[0-9]+.[0-9]+'
      #  - '[0-9]+.x'

jobs:
  build-and-publish-snapshots:
    runs-on: ubuntu-latest

    #permissions:
    #  id-token: write
    #  contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Publish snapshots to maven
        run: |
          ./gradlew publishNebulaPublicationToSnapshotsRepository
